name: test
on:
  pull_request:
env:
  SWIFT_DETERMINISTIC_HASHING: 1
  LOG_LEVEL: info

jobs:      
  linux:
    runs-on: ubuntu-latest
    container: swift:5.5-focal
    steps: 
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread
      - name: Verify release build
        timeout-minutes: 30
        run: swift build -c release
  
  macos:
    runs-on: macos-11
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: latest
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        timeout-minutes: 30
        run: |
          swift test -Xlinker -rpath \
                -Xlinker $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx

#  windows:
#    runs-on: windows-latest
#    steps:
#      - uses: compnerd/gha-setup-swift@main
#        with:
#          branch: swift-5.5-release
#          tag: 5.5-RELEASE
#      - name: Check out code
#        uses: actions/checkout@v2
#      - name: Run tests
#        run: swift test
