name: test
on:
  pull_request:

jobs:      
  linux:
    runs-on: ubuntu-latest
    container: swift:5.5-focal
    steps: 
      - name: Check out code
        uses: actions/checkout@v2
      #- name: Run tests
      #  timeout-minutes: 30
      #  run: swift test
      - name: Verify release build
        timeout-minutes: 30
        run: swift build -c release
  
  macos:
    runs-on: macos-11
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: latest
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        timeout-minutes: 30
        run: swift test

#  windows:
#    runs-on: windows-latest
#    steps:
#      - uses: compnerd/gha-setup-swift@main
#        with:
#          branch: swift-5.5-release
#          tag: 5.5-RELEASE
#      - name: Check out code
#        uses: actions/checkout@v2
#      - name: Run tests
#        run: swift test
